<a href="home.php">Home</a>
<a href="menu.php">Menu</a>
<a href="download.php">Download</a>
<a href="ebook.php">Ebook</a>
<a href="game.php">Game</a>
<a href="software.php">Software</a> 
<a href="grup.php">Grup</a>
<a href="elearning.php">E learning</a>
<a href="tutorial.php">Tutorial</a>
<a href="update.php">Update</a>  
<a href="smk.php">SMK 9 Medan</a>
<a href="daftarguru.php">Daftar Guru</a>
<a href="keterangan.php">Keterangan</a>
<a href="galeri.php">Galeri</a> 
<a href="Info Admin.php">Info Admin</a>
<a href="am.php">About Me</a>
<a href="gal.php">Galeri</a> 
<a href="register.php">Register</a>